frontend:
  baseurl: http://localhost:5173

application:
  uploads:
    path: uploads

spring:
  profiles:
    active: dev
  application:
    name: quadzone-api
    security:
      jwt:
        secret: K/gL4Rj8LqP6sUaF/R+dE/pA7vLzN/tS+bJ5wD/aE/gH+kF3jL8aU/wJ/yE7gE/dK/xH/vJ/qM/aA==
        expiration: 300000
        refresh-token:
          secret: mD/uJ/wP/sH/aE/gH+kF3jL8aU/wJ/yE7gE/dK/xH/vJ/qM/aK/gL4Rj8LqP6sUaF/R+dE/pA7vLzN/tS+bJ5wD==
          expiration: 86400000 # 1 day
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: quadzone04@gmail.com
    password: hiel wsxf kven mvht
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: warn

