frontend:
  baseurl: ${FRONTEND_BASE_URL:http://localhost:5173}

application:
  uploads:
    path: uploads

spring:
  profiles:
    active: dev
  application:
    name: quadzone-api
    security:
      jwt:
        secret: ${JWT_SECRET:K/gL4Rj8LqP6sUaF/R+dE/pA7vLzN/tS+bJ5wD/aE/gH+kF3jL8aU/wJ/yE7gE/dK/xH/vJ/qM/aA==}
        expiration: 300000
        refresh-token:
          secret: ${JWT_REFRESH_SECRET:mD/uJ/wP/sH/aE/gH+kF3jL8aU/wJ/yE7gE/dK/xH/vJ/qM/aK/gL4Rj8LqP6sUaF/R+dE/pA7vLzN/tS+bJ5wD==}
          expiration: 86400000 # 1 day
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:quadzone04@gmail.com}
    password: ${MAIL_PASSWORD:hiel wsxf kven mvht}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: warn
    com.quadzone.utils.email: info
