spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quadzone
    username: sa
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

aws:
  s3:
    access:
      key: 123 # change aws set-up
    secret:
      key: 123
  bucket-name: quadzone-uploads

jpa:
  hibernate:
    ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
        data-locations:
          classpath: db/insert.sql